set noerrorbells
set novisualbell
set nocompatible
set colorcolumn=81
syntax enable
set nobackup
set nowb
set noswapfile
set nomodeline
set background=dark
colorscheme solarized
map <Left> <Nop>
map <Right> <Nop>
map <Up> <Nop>
map <Down> <Nop>
